workspace:
  base: /go
  path: src/github.com/uswitch/kiam

pipeline:
  test:
    secrets: [ codecov_token ]
    image: golang:1.10
    commands:
      - make test
      - make coverage.txt
      - ./ci/codecov.sh

  benchmarks:
    image: golang:1.10
    commands:
      - make bench

  docker:
    when:
      event: push
    image: plugins/docker
    registry: quay.io
    repo: quay.io/uswitch/kiam
    secrets: [ docker_username, docker_password ]
    tags:
      - ${DRONE_COMMIT_SHA}
      - ${DRONE_COMMIT_BRANCH}

  docker-tagged:
    when:
      event: tag
    image: plugins/docker
    repo: quay.io/uswitch/kiam
    registry: quay.io
    secrets: [ docker_username, docker_password ]
    tags:
      - ${DRONE_TAG}

  helm:
    when:
      event: push
      branch: master
    image: registry.usw.co/drone/helm-s3
    secrets: [ aws_access_key_id, aws_secret_access_key ]
    environment:
      - AWS_REGION=eu-west-1
    commands:
      - helm repo add kiam-helm s3://kiam-helm/charts
      - helm package helm/kiam
      - helm s3 push *.tgz --ignore-if-exists kiam-helm
